#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admissions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="c2000")]
	public partial class StudentInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertsyStudent(syStudent instance);
    partial void UpdatesyStudent(syStudent instance);
    partial void DeletesyStudent(syStudent instance);
    #endregion
		
		public StudentInfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["c2000ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudentInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudentInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<syStudent> syStudents
		{
			get
			{
				return this.GetTable<syStudent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.syStudent")]
	public partial class syStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SSN;
		
		private int _AmTitleID;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _NickName;
		
		private string _MaidenName;
		
		private string _Addr1;
		
		private System.Nullable<char> _Addr2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private bool _BadAddr;
		
		private System.Nullable<int> _SyCountryID;
		
		private int _SyCountyID;
		
		private string _Phone;
		
		private string _WorkPhone;
		
		private string _Workext;
		
		private bool _BadPhone;
		
		private System.Nullable<System.DateTime> _LeadDate;
		
		private int _AmLeadTypeID;
		
		private int _AmSexID;
		
		private int _AmRaceID;
		
		private int _AmNationalityID;
		
		private int _AmMaritalID;
		
		private string _DrivLicState;
		
		private string _DrivLic;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _AlienNo;
		
		private int _AmAgencyID;
		
		private int _AmCitizenID;
		
		private string _email;
		
		private int _SySchoolStatusID;
		
		private int _AmRepID;
		
		private int _AmLeadSrcID;
		
		private int _SyCampusID;
		
		private int _AdProgramGroupID;
		
		private int _AdProgramID;
		
		private int _AdShiftID;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private int _AmPrevEducID;
		
		private int _AmHighSchoolID;
		
		private System.Nullable<int> _AmCollegeID;
		
		private System.Nullable<System.DateTime> _HsGradDate;
		
		private decimal _ARBalance;
		
		private short _NextTranNum;
		
		private string _ArAcctStat;
		
		private System.Nullable<System.DateTime> _StmtLastDate;
		
		private System.Nullable<System.DateTime> _StmtBeginDate;
		
		private System.Nullable<System.DateTime> _StmtCloseDate;
		
		private string _StmtComment;
		
		private System.Nullable<char> _DefaultAddressCode;
		
		private System.Nullable<int> _DefaultAddressID;
		
		private int _PlEmployerID;
		
		private int _plEmpStatusID;
		
		private string _StuNum;
		
		private System.Nullable<decimal> _PIN;
		
		private string _Comment;
		
		private System.Nullable<int> _AmExtraCurrID;
		
		private bool _Active;
		
		private bool _DataBlockIndicator;
		
		private char _ModFlag;
		
		private int _Userid;
		
		private System.DateTime _DateAdded;
		
		private System.DateTime _DateLstMod;
		
		private System.Data.Linq.Binary _ts;
		
		private int _SyStudentId;
		
		private char _Disabled;
		
		private char _Vet;
		
		private System.Nullable<int> _OriginalAmRepID;
		
		private System.Nullable<decimal> _CumGPA;
		
		private System.Nullable<decimal> _CumGPAPoints;
		
		private System.Nullable<System.DateTime> _CurrentLDA;
		
		private System.Nullable<decimal> _GPACredits;
		
		private System.Nullable<System.DateTime> _OriginalStartDate;
		
		private System.Nullable<System.DateTime> _OriginalExpStartDate;
		
		private string _OtherPhone;
		
		private string _OtherEmail;
		
		private System.Nullable<System.DateTime> _LastActivityDate;
		
		private System.Nullable<System.DateTime> _LastInterestDate;
		
		private System.Nullable<int> _DefaultMasterAddressID;
		
		private string _Suffix;
		
		private string _MiddleName;
		
		private bool _NIStudent;
		
		private string _StudentIdentifier;
		
		private string _BestTimeToContact;
		
		private System.Nullable<decimal> _PrevEducGPA;
		
		private bool _HSGraduated;
		
		private string _HSGraduationSession;
		
		private System.Nullable<System.DateTime> _HSDateEnrolled;
		
		private System.Nullable<System.DateTime> _HSLastDateAttended;
		
		private System.Nullable<int> _HSStudRank;
		
		private System.Nullable<int> _HSSchoolSize;
		
		private System.Nullable<byte> _HSTranscriptType;
		
		private System.Nullable<byte> _HSStudLevel;
		
		private string _HSGradYear;
		
		private string _LastName_FirstFour;
		
		private string _Zip_FirstThree;
		
		private System.Nullable<System.DateTime> _DBIModifiedDate;
		
		private string _RawLastName;
		
		private string _RawFirstName;
		
		private string _RawPhone;
		
		private string _ACGEligReasonCode;
		
		private System.Nullable<int> _FARigorousHighSchoolProgramCodeID;
		
		private System.Nullable<int> _CMSMSServiceProviderID;
		
		private bool _SubscribeToSMS;
		
		private string _MobileNumber;
		
		private char _SourceSystem;
		
		private System.Nullable<char> _IsHispanic;
		
		private bool _CrmSuppressFlag;
		
		private System.Nullable<int> _AmSuffixID;
		
		private bool _DDVeteran;
		
		private System.Nullable<decimal> _HSAcademicGPA;
		
		private string _AthleticID;
		
		private bool _InDistrict;
		
		private System.Nullable<System.DateTime> _faGradPlusCounselingDate;
		
		private bool _DefaultStipendsToEFT;
		
		private string _MI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSSNChanging(string value);
    partial void OnSSNChanged();
    partial void OnAmTitleIDChanging(int value);
    partial void OnAmTitleIDChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnMaidenNameChanging(string value);
    partial void OnMaidenNameChanged();
    partial void OnAddr1Changing(string value);
    partial void OnAddr1Changed();
    partial void OnAddr2Changing(System.Nullable<char> value);
    partial void OnAddr2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnBadAddrChanging(bool value);
    partial void OnBadAddrChanged();
    partial void OnSyCountryIDChanging(System.Nullable<int> value);
    partial void OnSyCountryIDChanged();
    partial void OnSyCountyIDChanging(int value);
    partial void OnSyCountyIDChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnWorkPhoneChanging(string value);
    partial void OnWorkPhoneChanged();
    partial void OnWorkextChanging(string value);
    partial void OnWorkextChanged();
    partial void OnBadPhoneChanging(bool value);
    partial void OnBadPhoneChanged();
    partial void OnLeadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLeadDateChanged();
    partial void OnAmLeadTypeIDChanging(int value);
    partial void OnAmLeadTypeIDChanged();
    partial void OnAmSexIDChanging(int value);
    partial void OnAmSexIDChanged();
    partial void OnAmRaceIDChanging(int value);
    partial void OnAmRaceIDChanged();
    partial void OnAmNationalityIDChanging(int value);
    partial void OnAmNationalityIDChanged();
    partial void OnAmMaritalIDChanging(int value);
    partial void OnAmMaritalIDChanged();
    partial void OnDrivLicStateChanging(string value);
    partial void OnDrivLicStateChanged();
    partial void OnDrivLicChanging(string value);
    partial void OnDrivLicChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnAlienNoChanging(string value);
    partial void OnAlienNoChanged();
    partial void OnAmAgencyIDChanging(int value);
    partial void OnAmAgencyIDChanged();
    partial void OnAmCitizenIDChanging(int value);
    partial void OnAmCitizenIDChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnSySchoolStatusIDChanging(int value);
    partial void OnSySchoolStatusIDChanged();
    partial void OnAmRepIDChanging(int value);
    partial void OnAmRepIDChanged();
    partial void OnAmLeadSrcIDChanging(int value);
    partial void OnAmLeadSrcIDChanged();
    partial void OnSyCampusIDChanging(int value);
    partial void OnSyCampusIDChanged();
    partial void OnAdProgramGroupIDChanging(int value);
    partial void OnAdProgramGroupIDChanged();
    partial void OnAdProgramIDChanging(int value);
    partial void OnAdProgramIDChanged();
    partial void OnAdShiftIDChanging(int value);
    partial void OnAdShiftIDChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnAmPrevEducIDChanging(int value);
    partial void OnAmPrevEducIDChanged();
    partial void OnAmHighSchoolIDChanging(int value);
    partial void OnAmHighSchoolIDChanged();
    partial void OnAmCollegeIDChanging(System.Nullable<int> value);
    partial void OnAmCollegeIDChanged();
    partial void OnHsGradDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHsGradDateChanged();
    partial void OnARBalanceChanging(decimal value);
    partial void OnARBalanceChanged();
    partial void OnNextTranNumChanging(short value);
    partial void OnNextTranNumChanged();
    partial void OnArAcctStatChanging(string value);
    partial void OnArAcctStatChanged();
    partial void OnStmtLastDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStmtLastDateChanged();
    partial void OnStmtBeginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStmtBeginDateChanged();
    partial void OnStmtCloseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStmtCloseDateChanged();
    partial void OnStmtCommentChanging(string value);
    partial void OnStmtCommentChanged();
    partial void OnDefaultAddressCodeChanging(System.Nullable<char> value);
    partial void OnDefaultAddressCodeChanged();
    partial void OnDefaultAddressIDChanging(System.Nullable<int> value);
    partial void OnDefaultAddressIDChanged();
    partial void OnPlEmployerIDChanging(int value);
    partial void OnPlEmployerIDChanged();
    partial void OnplEmpStatusIDChanging(int value);
    partial void OnplEmpStatusIDChanged();
    partial void OnStuNumChanging(string value);
    partial void OnStuNumChanged();
    partial void OnPINChanging(System.Nullable<decimal> value);
    partial void OnPINChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnAmExtraCurrIDChanging(System.Nullable<int> value);
    partial void OnAmExtraCurrIDChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnDataBlockIndicatorChanging(bool value);
    partial void OnDataBlockIndicatorChanged();
    partial void OnModFlagChanging(char value);
    partial void OnModFlagChanged();
    partial void OnUseridChanging(int value);
    partial void OnUseridChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    partial void OnDateLstModChanging(System.DateTime value);
    partial void OnDateLstModChanged();
    partial void OntsChanging(System.Data.Linq.Binary value);
    partial void OntsChanged();
    partial void OnSyStudentIdChanging(int value);
    partial void OnSyStudentIdChanged();
    partial void OnDisabledChanging(char value);
    partial void OnDisabledChanged();
    partial void OnVetChanging(char value);
    partial void OnVetChanged();
    partial void OnOriginalAmRepIDChanging(System.Nullable<int> value);
    partial void OnOriginalAmRepIDChanged();
    partial void OnCumGPAChanging(System.Nullable<decimal> value);
    partial void OnCumGPAChanged();
    partial void OnCumGPAPointsChanging(System.Nullable<decimal> value);
    partial void OnCumGPAPointsChanged();
    partial void OnCurrentLDAChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentLDAChanged();
    partial void OnGPACreditsChanging(System.Nullable<decimal> value);
    partial void OnGPACreditsChanged();
    partial void OnOriginalStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOriginalStartDateChanged();
    partial void OnOriginalExpStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOriginalExpStartDateChanged();
    partial void OnOtherPhoneChanging(string value);
    partial void OnOtherPhoneChanged();
    partial void OnOtherEmailChanging(string value);
    partial void OnOtherEmailChanged();
    partial void OnLastActivityDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityDateChanged();
    partial void OnLastInterestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastInterestDateChanged();
    partial void OnDefaultMasterAddressIDChanging(System.Nullable<int> value);
    partial void OnDefaultMasterAddressIDChanged();
    partial void OnSuffixChanging(string value);
    partial void OnSuffixChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnNIStudentChanging(bool value);
    partial void OnNIStudentChanged();
    partial void OnStudentIdentifierChanging(string value);
    partial void OnStudentIdentifierChanged();
    partial void OnBestTimeToContactChanging(string value);
    partial void OnBestTimeToContactChanged();
    partial void OnPrevEducGPAChanging(System.Nullable<decimal> value);
    partial void OnPrevEducGPAChanged();
    partial void OnHSGraduatedChanging(bool value);
    partial void OnHSGraduatedChanged();
    partial void OnHSGraduationSessionChanging(string value);
    partial void OnHSGraduationSessionChanged();
    partial void OnHSDateEnrolledChanging(System.Nullable<System.DateTime> value);
    partial void OnHSDateEnrolledChanged();
    partial void OnHSLastDateAttendedChanging(System.Nullable<System.DateTime> value);
    partial void OnHSLastDateAttendedChanged();
    partial void OnHSStudRankChanging(System.Nullable<int> value);
    partial void OnHSStudRankChanged();
    partial void OnHSSchoolSizeChanging(System.Nullable<int> value);
    partial void OnHSSchoolSizeChanged();
    partial void OnHSTranscriptTypeChanging(System.Nullable<byte> value);
    partial void OnHSTranscriptTypeChanged();
    partial void OnHSStudLevelChanging(System.Nullable<byte> value);
    partial void OnHSStudLevelChanged();
    partial void OnHSGradYearChanging(string value);
    partial void OnHSGradYearChanged();
    partial void OnLastName_FirstFourChanging(string value);
    partial void OnLastName_FirstFourChanged();
    partial void OnZip_FirstThreeChanging(string value);
    partial void OnZip_FirstThreeChanged();
    partial void OnDBIModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDBIModifiedDateChanged();
    partial void OnRawLastNameChanging(string value);
    partial void OnRawLastNameChanged();
    partial void OnRawFirstNameChanging(string value);
    partial void OnRawFirstNameChanged();
    partial void OnRawPhoneChanging(string value);
    partial void OnRawPhoneChanged();
    partial void OnACGEligReasonCodeChanging(string value);
    partial void OnACGEligReasonCodeChanged();
    partial void OnFARigorousHighSchoolProgramCodeIDChanging(System.Nullable<int> value);
    partial void OnFARigorousHighSchoolProgramCodeIDChanged();
    partial void OnCMSMSServiceProviderIDChanging(System.Nullable<int> value);
    partial void OnCMSMSServiceProviderIDChanged();
    partial void OnSubscribeToSMSChanging(bool value);
    partial void OnSubscribeToSMSChanged();
    partial void OnMobileNumberChanging(string value);
    partial void OnMobileNumberChanged();
    partial void OnSourceSystemChanging(char value);
    partial void OnSourceSystemChanged();
    partial void OnIsHispanicChanging(System.Nullable<char> value);
    partial void OnIsHispanicChanged();
    partial void OnCrmSuppressFlagChanging(bool value);
    partial void OnCrmSuppressFlagChanged();
    partial void OnAmSuffixIDChanging(System.Nullable<int> value);
    partial void OnAmSuffixIDChanged();
    partial void OnDDVeteranChanging(bool value);
    partial void OnDDVeteranChanged();
    partial void OnHSAcademicGPAChanging(System.Nullable<decimal> value);
    partial void OnHSAcademicGPAChanged();
    partial void OnAthleticIDChanging(string value);
    partial void OnAthleticIDChanged();
    partial void OnInDistrictChanging(bool value);
    partial void OnInDistrictChanged();
    partial void OnfaGradPlusCounselingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnfaGradPlusCounselingDateChanged();
    partial void OnDefaultStipendsToEFTChanging(bool value);
    partial void OnDefaultStipendsToEFTChanged();
    partial void OnMIChanging(string value);
    partial void OnMIChanged();
    #endregion
		
		public syStudent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string SSN
		{
			get
			{
				return this._SSN;
			}
			set
			{
				if ((this._SSN != value))
				{
					this.OnSSNChanging(value);
					this.SendPropertyChanging();
					this._SSN = value;
					this.SendPropertyChanged("SSN");
					this.OnSSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmTitleID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmTitleID
		{
			get
			{
				return this._AmTitleID;
			}
			set
			{
				if ((this._AmTitleID != value))
				{
					this.OnAmTitleIDChanging(value);
					this.SendPropertyChanging();
					this._AmTitleID = value;
					this.SendPropertyChanged("AmTitleID");
					this.OnAmTitleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(25) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(25) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="VarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaidenName", DbType="VarChar(19) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MaidenName
		{
			get
			{
				return this._MaidenName;
			}
			set
			{
				if ((this._MaidenName != value))
				{
					this.OnMaidenNameChanging(value);
					this.SendPropertyChanging();
					this._MaidenName = value;
					this.SendPropertyChanged("MaidenName");
					this.OnMaidenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr1", DbType="VarChar(255) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Addr1
		{
			get
			{
				return this._Addr1;
			}
			set
			{
				if ((this._Addr1 != value))
				{
					this.OnAddr1Changing(value);
					this.SendPropertyChanging();
					this._Addr1 = value;
					this.SendPropertyChanged("Addr1");
					this.OnAddr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr2", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> Addr2
		{
			get
			{
				return this._Addr2;
			}
			set
			{
				if ((this._Addr2 != value))
				{
					this.OnAddr2Changing(value);
					this.SendPropertyChanging();
					this._Addr2 = value;
					this.SendPropertyChanged("Addr2");
					this.OnAddr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(25) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Char(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadAddr", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool BadAddr
		{
			get
			{
				return this._BadAddr;
			}
			set
			{
				if ((this._BadAddr != value))
				{
					this.OnBadAddrChanging(value);
					this.SendPropertyChanging();
					this._BadAddr = value;
					this.SendPropertyChanged("BadAddr");
					this.OnBadAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyCountryID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> SyCountryID
		{
			get
			{
				return this._SyCountryID;
			}
			set
			{
				if ((this._SyCountryID != value))
				{
					this.OnSyCountryIDChanging(value);
					this.SendPropertyChanging();
					this._SyCountryID = value;
					this.SendPropertyChanged("SyCountryID");
					this.OnSyCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyCountyID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int SyCountyID
		{
			get
			{
				return this._SyCountyID;
			}
			set
			{
				if ((this._SyCountyID != value))
				{
					this.OnSyCountyIDChanging(value);
					this.SendPropertyChanging();
					this._SyCountyID = value;
					this.SendPropertyChanged("SyCountyID");
					this.OnSyCountyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Char(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPhone", DbType="Char(16) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string WorkPhone
		{
			get
			{
				return this._WorkPhone;
			}
			set
			{
				if ((this._WorkPhone != value))
				{
					this.OnWorkPhoneChanging(value);
					this.SendPropertyChanging();
					this._WorkPhone = value;
					this.SendPropertyChanged("WorkPhone");
					this.OnWorkPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Workext", DbType="VarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Workext
		{
			get
			{
				return this._Workext;
			}
			set
			{
				if ((this._Workext != value))
				{
					this.OnWorkextChanging(value);
					this.SendPropertyChanging();
					this._Workext = value;
					this.SendPropertyChanged("Workext");
					this.OnWorkextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadPhone", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool BadPhone
		{
			get
			{
				return this._BadPhone;
			}
			set
			{
				if ((this._BadPhone != value))
				{
					this.OnBadPhoneChanging(value);
					this.SendPropertyChanging();
					this._BadPhone = value;
					this.SendPropertyChanged("BadPhone");
					this.OnBadPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeadDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> LeadDate
		{
			get
			{
				return this._LeadDate;
			}
			set
			{
				if ((this._LeadDate != value))
				{
					this.OnLeadDateChanging(value);
					this.SendPropertyChanging();
					this._LeadDate = value;
					this.SendPropertyChanged("LeadDate");
					this.OnLeadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmLeadTypeID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmLeadTypeID
		{
			get
			{
				return this._AmLeadTypeID;
			}
			set
			{
				if ((this._AmLeadTypeID != value))
				{
					this.OnAmLeadTypeIDChanging(value);
					this.SendPropertyChanging();
					this._AmLeadTypeID = value;
					this.SendPropertyChanged("AmLeadTypeID");
					this.OnAmLeadTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmSexID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmSexID
		{
			get
			{
				return this._AmSexID;
			}
			set
			{
				if ((this._AmSexID != value))
				{
					this.OnAmSexIDChanging(value);
					this.SendPropertyChanging();
					this._AmSexID = value;
					this.SendPropertyChanged("AmSexID");
					this.OnAmSexIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmRaceID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmRaceID
		{
			get
			{
				return this._AmRaceID;
			}
			set
			{
				if ((this._AmRaceID != value))
				{
					this.OnAmRaceIDChanging(value);
					this.SendPropertyChanging();
					this._AmRaceID = value;
					this.SendPropertyChanged("AmRaceID");
					this.OnAmRaceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmNationalityID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmNationalityID
		{
			get
			{
				return this._AmNationalityID;
			}
			set
			{
				if ((this._AmNationalityID != value))
				{
					this.OnAmNationalityIDChanging(value);
					this.SendPropertyChanging();
					this._AmNationalityID = value;
					this.SendPropertyChanged("AmNationalityID");
					this.OnAmNationalityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmMaritalID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmMaritalID
		{
			get
			{
				return this._AmMaritalID;
			}
			set
			{
				if ((this._AmMaritalID != value))
				{
					this.OnAmMaritalIDChanging(value);
					this.SendPropertyChanging();
					this._AmMaritalID = value;
					this.SendPropertyChanged("AmMaritalID");
					this.OnAmMaritalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivLicState", DbType="Char(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DrivLicState
		{
			get
			{
				return this._DrivLicState;
			}
			set
			{
				if ((this._DrivLicState != value))
				{
					this.OnDrivLicStateChanging(value);
					this.SendPropertyChanging();
					this._DrivLicState = value;
					this.SendPropertyChanged("DrivLicState");
					this.OnDrivLicStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrivLic", DbType="Char(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DrivLic
		{
			get
			{
				return this._DrivLic;
			}
			set
			{
				if ((this._DrivLic != value))
				{
					this.OnDrivLicChanging(value);
					this.SendPropertyChanging();
					this._DrivLic = value;
					this.SendPropertyChanged("DrivLic");
					this.OnDrivLicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlienNo", DbType="Char(9)", UpdateCheck=UpdateCheck.Never)]
		public string AlienNo
		{
			get
			{
				return this._AlienNo;
			}
			set
			{
				if ((this._AlienNo != value))
				{
					this.OnAlienNoChanging(value);
					this.SendPropertyChanging();
					this._AlienNo = value;
					this.SendPropertyChanged("AlienNo");
					this.OnAlienNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmAgencyID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmAgencyID
		{
			get
			{
				return this._AmAgencyID;
			}
			set
			{
				if ((this._AmAgencyID != value))
				{
					this.OnAmAgencyIDChanging(value);
					this.SendPropertyChanging();
					this._AmAgencyID = value;
					this.SendPropertyChanged("AmAgencyID");
					this.OnAmAgencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmCitizenID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmCitizenID
		{
			get
			{
				return this._AmCitizenID;
			}
			set
			{
				if ((this._AmCitizenID != value))
				{
					this.OnAmCitizenIDChanging(value);
					this.SendPropertyChanging();
					this._AmCitizenID = value;
					this.SendPropertyChanged("AmCitizenID");
					this.OnAmCitizenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SySchoolStatusID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int SySchoolStatusID
		{
			get
			{
				return this._SySchoolStatusID;
			}
			set
			{
				if ((this._SySchoolStatusID != value))
				{
					this.OnSySchoolStatusIDChanging(value);
					this.SendPropertyChanging();
					this._SySchoolStatusID = value;
					this.SendPropertyChanged("SySchoolStatusID");
					this.OnSySchoolStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmRepID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmRepID
		{
			get
			{
				return this._AmRepID;
			}
			set
			{
				if ((this._AmRepID != value))
				{
					this.OnAmRepIDChanging(value);
					this.SendPropertyChanging();
					this._AmRepID = value;
					this.SendPropertyChanged("AmRepID");
					this.OnAmRepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmLeadSrcID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmLeadSrcID
		{
			get
			{
				return this._AmLeadSrcID;
			}
			set
			{
				if ((this._AmLeadSrcID != value))
				{
					this.OnAmLeadSrcIDChanging(value);
					this.SendPropertyChanging();
					this._AmLeadSrcID = value;
					this.SendPropertyChanged("AmLeadSrcID");
					this.OnAmLeadSrcIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyCampusID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int SyCampusID
		{
			get
			{
				return this._SyCampusID;
			}
			set
			{
				if ((this._SyCampusID != value))
				{
					this.OnSyCampusIDChanging(value);
					this.SendPropertyChanging();
					this._SyCampusID = value;
					this.SendPropertyChanged("SyCampusID");
					this.OnSyCampusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdProgramGroupID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AdProgramGroupID
		{
			get
			{
				return this._AdProgramGroupID;
			}
			set
			{
				if ((this._AdProgramGroupID != value))
				{
					this.OnAdProgramGroupIDChanging(value);
					this.SendPropertyChanging();
					this._AdProgramGroupID = value;
					this.SendPropertyChanged("AdProgramGroupID");
					this.OnAdProgramGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdProgramID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AdProgramID
		{
			get
			{
				return this._AdProgramID;
			}
			set
			{
				if ((this._AdProgramID != value))
				{
					this.OnAdProgramIDChanging(value);
					this.SendPropertyChanging();
					this._AdProgramID = value;
					this.SendPropertyChanged("AdProgramID");
					this.OnAdProgramIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdShiftID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AdShiftID
		{
			get
			{
				return this._AdShiftID;
			}
			set
			{
				if ((this._AdShiftID != value))
				{
					this.OnAdShiftIDChanging(value);
					this.SendPropertyChanging();
					this._AdShiftID = value;
					this.SendPropertyChanged("AdShiftID");
					this.OnAdShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmPrevEducID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmPrevEducID
		{
			get
			{
				return this._AmPrevEducID;
			}
			set
			{
				if ((this._AmPrevEducID != value))
				{
					this.OnAmPrevEducIDChanging(value);
					this.SendPropertyChanging();
					this._AmPrevEducID = value;
					this.SendPropertyChanged("AmPrevEducID");
					this.OnAmPrevEducIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmHighSchoolID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int AmHighSchoolID
		{
			get
			{
				return this._AmHighSchoolID;
			}
			set
			{
				if ((this._AmHighSchoolID != value))
				{
					this.OnAmHighSchoolIDChanging(value);
					this.SendPropertyChanging();
					this._AmHighSchoolID = value;
					this.SendPropertyChanged("AmHighSchoolID");
					this.OnAmHighSchoolIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmCollegeID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AmCollegeID
		{
			get
			{
				return this._AmCollegeID;
			}
			set
			{
				if ((this._AmCollegeID != value))
				{
					this.OnAmCollegeIDChanging(value);
					this.SendPropertyChanging();
					this._AmCollegeID = value;
					this.SendPropertyChanged("AmCollegeID");
					this.OnAmCollegeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HsGradDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> HsGradDate
		{
			get
			{
				return this._HsGradDate;
			}
			set
			{
				if ((this._HsGradDate != value))
				{
					this.OnHsGradDateChanging(value);
					this.SendPropertyChanging();
					this._HsGradDate = value;
					this.SendPropertyChanged("HsGradDate");
					this.OnHsGradDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARBalance", DbType="Money NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public decimal ARBalance
		{
			get
			{
				return this._ARBalance;
			}
			set
			{
				if ((this._ARBalance != value))
				{
					this.OnARBalanceChanging(value);
					this.SendPropertyChanging();
					this._ARBalance = value;
					this.SendPropertyChanged("ARBalance");
					this.OnARBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextTranNum", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short NextTranNum
		{
			get
			{
				return this._NextTranNum;
			}
			set
			{
				if ((this._NextTranNum != value))
				{
					this.OnNextTranNumChanging(value);
					this.SendPropertyChanging();
					this._NextTranNum = value;
					this.SendPropertyChanged("NextTranNum");
					this.OnNextTranNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArAcctStat", DbType="Char(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ArAcctStat
		{
			get
			{
				return this._ArAcctStat;
			}
			set
			{
				if ((this._ArAcctStat != value))
				{
					this.OnArAcctStatChanging(value);
					this.SendPropertyChanging();
					this._ArAcctStat = value;
					this.SendPropertyChanged("ArAcctStat");
					this.OnArAcctStatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtLastDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> StmtLastDate
		{
			get
			{
				return this._StmtLastDate;
			}
			set
			{
				if ((this._StmtLastDate != value))
				{
					this.OnStmtLastDateChanging(value);
					this.SendPropertyChanging();
					this._StmtLastDate = value;
					this.SendPropertyChanged("StmtLastDate");
					this.OnStmtLastDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtBeginDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> StmtBeginDate
		{
			get
			{
				return this._StmtBeginDate;
			}
			set
			{
				if ((this._StmtBeginDate != value))
				{
					this.OnStmtBeginDateChanging(value);
					this.SendPropertyChanging();
					this._StmtBeginDate = value;
					this.SendPropertyChanged("StmtBeginDate");
					this.OnStmtBeginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtCloseDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> StmtCloseDate
		{
			get
			{
				return this._StmtCloseDate;
			}
			set
			{
				if ((this._StmtCloseDate != value))
				{
					this.OnStmtCloseDateChanging(value);
					this.SendPropertyChanging();
					this._StmtCloseDate = value;
					this.SendPropertyChanged("StmtCloseDate");
					this.OnStmtCloseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StmtComment", DbType="VarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string StmtComment
		{
			get
			{
				return this._StmtComment;
			}
			set
			{
				if ((this._StmtComment != value))
				{
					this.OnStmtCommentChanging(value);
					this.SendPropertyChanging();
					this._StmtComment = value;
					this.SendPropertyChanged("StmtComment");
					this.OnStmtCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultAddressCode", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> DefaultAddressCode
		{
			get
			{
				return this._DefaultAddressCode;
			}
			set
			{
				if ((this._DefaultAddressCode != value))
				{
					this.OnDefaultAddressCodeChanging(value);
					this.SendPropertyChanging();
					this._DefaultAddressCode = value;
					this.SendPropertyChanged("DefaultAddressCode");
					this.OnDefaultAddressCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultAddressID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DefaultAddressID
		{
			get
			{
				return this._DefaultAddressID;
			}
			set
			{
				if ((this._DefaultAddressID != value))
				{
					this.OnDefaultAddressIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultAddressID = value;
					this.SendPropertyChanged("DefaultAddressID");
					this.OnDefaultAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlEmployerID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int PlEmployerID
		{
			get
			{
				return this._PlEmployerID;
			}
			set
			{
				if ((this._PlEmployerID != value))
				{
					this.OnPlEmployerIDChanging(value);
					this.SendPropertyChanging();
					this._PlEmployerID = value;
					this.SendPropertyChanged("PlEmployerID");
					this.OnPlEmployerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plEmpStatusID", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int plEmpStatusID
		{
			get
			{
				return this._plEmpStatusID;
			}
			set
			{
				if ((this._plEmpStatusID != value))
				{
					this.OnplEmpStatusIDChanging(value);
					this.SendPropertyChanging();
					this._plEmpStatusID = value;
					this.SendPropertyChanged("plEmpStatusID");
					this.OnplEmpStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuNum", DbType="Char(10)", UpdateCheck=UpdateCheck.Never)]
		public string StuNum
		{
			get
			{
				return this._StuNum;
			}
			set
			{
				if ((this._StuNum != value))
				{
					this.OnStuNumChanging(value);
					this.SendPropertyChanging();
					this._StuNum = value;
					this.SendPropertyChanged("StuNum");
					this.OnStuNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Decimal(4,0)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> PIN
		{
			get
			{
				return this._PIN;
			}
			set
			{
				if ((this._PIN != value))
				{
					this.OnPINChanging(value);
					this.SendPropertyChanging();
					this._PIN = value;
					this.SendPropertyChanged("PIN");
					this.OnPINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmExtraCurrID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AmExtraCurrID
		{
			get
			{
				return this._AmExtraCurrID;
			}
			set
			{
				if ((this._AmExtraCurrID != value))
				{
					this.OnAmExtraCurrIDChanging(value);
					this.SendPropertyChanging();
					this._AmExtraCurrID = value;
					this.SendPropertyChanged("AmExtraCurrID");
					this.OnAmExtraCurrIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataBlockIndicator", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool DataBlockIndicator
		{
			get
			{
				return this._DataBlockIndicator;
			}
			set
			{
				if ((this._DataBlockIndicator != value))
				{
					this.OnDataBlockIndicatorChanging(value);
					this.SendPropertyChanging();
					this._DataBlockIndicator = value;
					this.SendPropertyChanged("DataBlockIndicator");
					this.OnDataBlockIndicatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModFlag", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char ModFlag
		{
			get
			{
				return this._ModFlag;
			}
			set
			{
				if ((this._ModFlag != value))
				{
					this.OnModFlagChanging(value);
					this.SendPropertyChanging();
					this._ModFlag = value;
					this.SendPropertyChanged("ModFlag");
					this.OnModFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Userid", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Userid
		{
			get
			{
				return this._Userid;
			}
			set
			{
				if ((this._Userid != value))
				{
					this.OnUseridChanging(value);
					this.SendPropertyChanging();
					this._Userid = value;
					this.SendPropertyChanged("Userid");
					this.OnUseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLstMod", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DateLstMod
		{
			get
			{
				return this._DateLstMod;
			}
			set
			{
				if ((this._DateLstMod != value))
				{
					this.OnDateLstModChanging(value);
					this.SendPropertyChanging();
					this._DateLstMod = value;
					this.SendPropertyChanged("DateLstMod");
					this.OnDateLstModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SyStudentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int SyStudentId
		{
			get
			{
				return this._SyStudentId;
			}
			set
			{
				if ((this._SyStudentId != value))
				{
					this.OnSyStudentIdChanging(value);
					this.SendPropertyChanging();
					this._SyStudentId = value;
					this.SendPropertyChanged("SyStudentId");
					this.OnSyStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vet", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char Vet
		{
			get
			{
				return this._Vet;
			}
			set
			{
				if ((this._Vet != value))
				{
					this.OnVetChanging(value);
					this.SendPropertyChanging();
					this._Vet = value;
					this.SendPropertyChanged("Vet");
					this.OnVetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalAmRepID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> OriginalAmRepID
		{
			get
			{
				return this._OriginalAmRepID;
			}
			set
			{
				if ((this._OriginalAmRepID != value))
				{
					this.OnOriginalAmRepIDChanging(value);
					this.SendPropertyChanging();
					this._OriginalAmRepID = value;
					this.SendPropertyChanged("OriginalAmRepID");
					this.OnOriginalAmRepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CumGPA", DbType="Decimal(11,6)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> CumGPA
		{
			get
			{
				return this._CumGPA;
			}
			set
			{
				if ((this._CumGPA != value))
				{
					this.OnCumGPAChanging(value);
					this.SendPropertyChanging();
					this._CumGPA = value;
					this.SendPropertyChanged("CumGPA");
					this.OnCumGPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CumGPAPoints", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> CumGPAPoints
		{
			get
			{
				return this._CumGPAPoints;
			}
			set
			{
				if ((this._CumGPAPoints != value))
				{
					this.OnCumGPAPointsChanging(value);
					this.SendPropertyChanging();
					this._CumGPAPoints = value;
					this.SendPropertyChanged("CumGPAPoints");
					this.OnCumGPAPointsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentLDA", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> CurrentLDA
		{
			get
			{
				return this._CurrentLDA;
			}
			set
			{
				if ((this._CurrentLDA != value))
				{
					this.OnCurrentLDAChanging(value);
					this.SendPropertyChanging();
					this._CurrentLDA = value;
					this.SendPropertyChanged("CurrentLDA");
					this.OnCurrentLDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPACredits", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> GPACredits
		{
			get
			{
				return this._GPACredits;
			}
			set
			{
				if ((this._GPACredits != value))
				{
					this.OnGPACreditsChanging(value);
					this.SendPropertyChanging();
					this._GPACredits = value;
					this.SendPropertyChanged("GPACredits");
					this.OnGPACreditsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalStartDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> OriginalStartDate
		{
			get
			{
				return this._OriginalStartDate;
			}
			set
			{
				if ((this._OriginalStartDate != value))
				{
					this.OnOriginalStartDateChanging(value);
					this.SendPropertyChanging();
					this._OriginalStartDate = value;
					this.SendPropertyChanged("OriginalStartDate");
					this.OnOriginalStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalExpStartDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> OriginalExpStartDate
		{
			get
			{
				return this._OriginalExpStartDate;
			}
			set
			{
				if ((this._OriginalExpStartDate != value))
				{
					this.OnOriginalExpStartDateChanging(value);
					this.SendPropertyChanging();
					this._OriginalExpStartDate = value;
					this.SendPropertyChanged("OriginalExpStartDate");
					this.OnOriginalExpStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherPhone", DbType="Char(16)", UpdateCheck=UpdateCheck.Never)]
		public string OtherPhone
		{
			get
			{
				return this._OtherPhone;
			}
			set
			{
				if ((this._OtherPhone != value))
				{
					this.OnOtherPhoneChanging(value);
					this.SendPropertyChanging();
					this._OtherPhone = value;
					this.SendPropertyChanged("OtherPhone");
					this.OnOtherPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherEmail", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string OtherEmail
		{
			get
			{
				return this._OtherEmail;
			}
			set
			{
				if ((this._OtherEmail != value))
				{
					this.OnOtherEmailChanging(value);
					this.SendPropertyChanging();
					this._OtherEmail = value;
					this.SendPropertyChanged("OtherEmail");
					this.OnOtherEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastInterestDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> LastInterestDate
		{
			get
			{
				return this._LastInterestDate;
			}
			set
			{
				if ((this._LastInterestDate != value))
				{
					this.OnLastInterestDateChanging(value);
					this.SendPropertyChanging();
					this._LastInterestDate = value;
					this.SendPropertyChanged("LastInterestDate");
					this.OnLastInterestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultMasterAddressID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DefaultMasterAddressID
		{
			get
			{
				return this._DefaultMasterAddressID;
			}
			set
			{
				if ((this._DefaultMasterAddressID != value))
				{
					this.OnDefaultMasterAddressIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultMasterAddressID = value;
					this.SendPropertyChanged("DefaultMasterAddressID");
					this.OnDefaultMasterAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suffix", DbType="Char(3)", UpdateCheck=UpdateCheck.Never)]
		public string Suffix
		{
			get
			{
				return this._Suffix;
			}
			set
			{
				if ((this._Suffix != value))
				{
					this.OnSuffixChanging(value);
					this.SendPropertyChanging();
					this._Suffix = value;
					this.SendPropertyChanged("Suffix");
					this.OnSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIStudent", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool NIStudent
		{
			get
			{
				return this._NIStudent;
			}
			set
			{
				if ((this._NIStudent != value))
				{
					this.OnNIStudentChanging(value);
					this.SendPropertyChanging();
					this._NIStudent = value;
					this.SendPropertyChanged("NIStudent");
					this.OnNIStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentIdentifier", DbType="VarChar(44)", UpdateCheck=UpdateCheck.Never)]
		public string StudentIdentifier
		{
			get
			{
				return this._StudentIdentifier;
			}
			set
			{
				if ((this._StudentIdentifier != value))
				{
					this.OnStudentIdentifierChanging(value);
					this.SendPropertyChanging();
					this._StudentIdentifier = value;
					this.SendPropertyChanged("StudentIdentifier");
					this.OnStudentIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestTimeToContact", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string BestTimeToContact
		{
			get
			{
				return this._BestTimeToContact;
			}
			set
			{
				if ((this._BestTimeToContact != value))
				{
					this.OnBestTimeToContactChanging(value);
					this.SendPropertyChanging();
					this._BestTimeToContact = value;
					this.SendPropertyChanged("BestTimeToContact");
					this.OnBestTimeToContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrevEducGPA", DbType="Decimal(11,6)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> PrevEducGPA
		{
			get
			{
				return this._PrevEducGPA;
			}
			set
			{
				if ((this._PrevEducGPA != value))
				{
					this.OnPrevEducGPAChanging(value);
					this.SendPropertyChanging();
					this._PrevEducGPA = value;
					this.SendPropertyChanged("PrevEducGPA");
					this.OnPrevEducGPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSGraduated", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool HSGraduated
		{
			get
			{
				return this._HSGraduated;
			}
			set
			{
				if ((this._HSGraduated != value))
				{
					this.OnHSGraduatedChanging(value);
					this.SendPropertyChanging();
					this._HSGraduated = value;
					this.SendPropertyChanged("HSGraduated");
					this.OnHSGraduatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSGraduationSession", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string HSGraduationSession
		{
			get
			{
				return this._HSGraduationSession;
			}
			set
			{
				if ((this._HSGraduationSession != value))
				{
					this.OnHSGraduationSessionChanging(value);
					this.SendPropertyChanging();
					this._HSGraduationSession = value;
					this.SendPropertyChanged("HSGraduationSession");
					this.OnHSGraduationSessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSDateEnrolled", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> HSDateEnrolled
		{
			get
			{
				return this._HSDateEnrolled;
			}
			set
			{
				if ((this._HSDateEnrolled != value))
				{
					this.OnHSDateEnrolledChanging(value);
					this.SendPropertyChanging();
					this._HSDateEnrolled = value;
					this.SendPropertyChanged("HSDateEnrolled");
					this.OnHSDateEnrolledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSLastDateAttended", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> HSLastDateAttended
		{
			get
			{
				return this._HSLastDateAttended;
			}
			set
			{
				if ((this._HSLastDateAttended != value))
				{
					this.OnHSLastDateAttendedChanging(value);
					this.SendPropertyChanging();
					this._HSLastDateAttended = value;
					this.SendPropertyChanged("HSLastDateAttended");
					this.OnHSLastDateAttendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSStudRank", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> HSStudRank
		{
			get
			{
				return this._HSStudRank;
			}
			set
			{
				if ((this._HSStudRank != value))
				{
					this.OnHSStudRankChanging(value);
					this.SendPropertyChanging();
					this._HSStudRank = value;
					this.SendPropertyChanged("HSStudRank");
					this.OnHSStudRankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSSchoolSize", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> HSSchoolSize
		{
			get
			{
				return this._HSSchoolSize;
			}
			set
			{
				if ((this._HSSchoolSize != value))
				{
					this.OnHSSchoolSizeChanging(value);
					this.SendPropertyChanging();
					this._HSSchoolSize = value;
					this.SendPropertyChanged("HSSchoolSize");
					this.OnHSSchoolSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSTranscriptType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> HSTranscriptType
		{
			get
			{
				return this._HSTranscriptType;
			}
			set
			{
				if ((this._HSTranscriptType != value))
				{
					this.OnHSTranscriptTypeChanging(value);
					this.SendPropertyChanging();
					this._HSTranscriptType = value;
					this.SendPropertyChanged("HSTranscriptType");
					this.OnHSTranscriptTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSStudLevel", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> HSStudLevel
		{
			get
			{
				return this._HSStudLevel;
			}
			set
			{
				if ((this._HSStudLevel != value))
				{
					this.OnHSStudLevelChanging(value);
					this.SendPropertyChanging();
					this._HSStudLevel = value;
					this.SendPropertyChanged("HSStudLevel");
					this.OnHSStudLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSGradYear", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string HSGradYear
		{
			get
			{
				return this._HSGradYear;
			}
			set
			{
				if ((this._HSGradYear != value))
				{
					this.OnHSGradYearChanging(value);
					this.SendPropertyChanging();
					this._HSGradYear = value;
					this.SendPropertyChanged("HSGradYear");
					this.OnHSGradYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName_FirstFour", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string LastName_FirstFour
		{
			get
			{
				return this._LastName_FirstFour;
			}
			set
			{
				if ((this._LastName_FirstFour != value))
				{
					this.OnLastName_FirstFourChanging(value);
					this.SendPropertyChanging();
					this._LastName_FirstFour = value;
					this.SendPropertyChanged("LastName_FirstFour");
					this.OnLastName_FirstFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_FirstThree", DbType="VarChar(3)", UpdateCheck=UpdateCheck.Never)]
		public string Zip_FirstThree
		{
			get
			{
				return this._Zip_FirstThree;
			}
			set
			{
				if ((this._Zip_FirstThree != value))
				{
					this.OnZip_FirstThreeChanging(value);
					this.SendPropertyChanging();
					this._Zip_FirstThree = value;
					this.SendPropertyChanged("Zip_FirstThree");
					this.OnZip_FirstThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBIModifiedDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DBIModifiedDate
		{
			get
			{
				return this._DBIModifiedDate;
			}
			set
			{
				if ((this._DBIModifiedDate != value))
				{
					this.OnDBIModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._DBIModifiedDate = value;
					this.SendPropertyChanged("DBIModifiedDate");
					this.OnDBIModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawLastName", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string RawLastName
		{
			get
			{
				return this._RawLastName;
			}
			set
			{
				if ((this._RawLastName != value))
				{
					this.OnRawLastNameChanging(value);
					this.SendPropertyChanging();
					this._RawLastName = value;
					this.SendPropertyChanged("RawLastName");
					this.OnRawLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawFirstName", DbType="VarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string RawFirstName
		{
			get
			{
				return this._RawFirstName;
			}
			set
			{
				if ((this._RawFirstName != value))
				{
					this.OnRawFirstNameChanging(value);
					this.SendPropertyChanging();
					this._RawFirstName = value;
					this.SendPropertyChanged("RawFirstName");
					this.OnRawFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawPhone", DbType="VarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string RawPhone
		{
			get
			{
				return this._RawPhone;
			}
			set
			{
				if ((this._RawPhone != value))
				{
					this.OnRawPhoneChanging(value);
					this.SendPropertyChanging();
					this._RawPhone = value;
					this.SendPropertyChanged("RawPhone");
					this.OnRawPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACGEligReasonCode", DbType="Char(2)", UpdateCheck=UpdateCheck.Never)]
		public string ACGEligReasonCode
		{
			get
			{
				return this._ACGEligReasonCode;
			}
			set
			{
				if ((this._ACGEligReasonCode != value))
				{
					this.OnACGEligReasonCodeChanging(value);
					this.SendPropertyChanging();
					this._ACGEligReasonCode = value;
					this.SendPropertyChanged("ACGEligReasonCode");
					this.OnACGEligReasonCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FARigorousHighSchoolProgramCodeID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FARigorousHighSchoolProgramCodeID
		{
			get
			{
				return this._FARigorousHighSchoolProgramCodeID;
			}
			set
			{
				if ((this._FARigorousHighSchoolProgramCodeID != value))
				{
					this.OnFARigorousHighSchoolProgramCodeIDChanging(value);
					this.SendPropertyChanging();
					this._FARigorousHighSchoolProgramCodeID = value;
					this.SendPropertyChanged("FARigorousHighSchoolProgramCodeID");
					this.OnFARigorousHighSchoolProgramCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMSMSServiceProviderID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CMSMSServiceProviderID
		{
			get
			{
				return this._CMSMSServiceProviderID;
			}
			set
			{
				if ((this._CMSMSServiceProviderID != value))
				{
					this.OnCMSMSServiceProviderIDChanging(value);
					this.SendPropertyChanging();
					this._CMSMSServiceProviderID = value;
					this.SendPropertyChanged("CMSMSServiceProviderID");
					this.OnCMSMSServiceProviderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscribeToSMS", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool SubscribeToSMS
		{
			get
			{
				return this._SubscribeToSMS;
			}
			set
			{
				if ((this._SubscribeToSMS != value))
				{
					this.OnSubscribeToSMSChanging(value);
					this.SendPropertyChanging();
					this._SubscribeToSMS = value;
					this.SendPropertyChanged("SubscribeToSMS");
					this.OnSubscribeToSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="VarChar(16)", UpdateCheck=UpdateCheck.Never)]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this.OnMobileNumberChanging(value);
					this.SendPropertyChanging();
					this._MobileNumber = value;
					this.SendPropertyChanged("MobileNumber");
					this.OnMobileNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceSystem", DbType="Char(1) NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public char SourceSystem
		{
			get
			{
				return this._SourceSystem;
			}
			set
			{
				if ((this._SourceSystem != value))
				{
					this.OnSourceSystemChanging(value);
					this.SendPropertyChanging();
					this._SourceSystem = value;
					this.SendPropertyChanged("SourceSystem");
					this.OnSourceSystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHispanic", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> IsHispanic
		{
			get
			{
				return this._IsHispanic;
			}
			set
			{
				if ((this._IsHispanic != value))
				{
					this.OnIsHispanicChanging(value);
					this.SendPropertyChanging();
					this._IsHispanic = value;
					this.SendPropertyChanged("IsHispanic");
					this.OnIsHispanicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrmSuppressFlag", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool CrmSuppressFlag
		{
			get
			{
				return this._CrmSuppressFlag;
			}
			set
			{
				if ((this._CrmSuppressFlag != value))
				{
					this.OnCrmSuppressFlagChanging(value);
					this.SendPropertyChanging();
					this._CrmSuppressFlag = value;
					this.SendPropertyChanged("CrmSuppressFlag");
					this.OnCrmSuppressFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmSuffixID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> AmSuffixID
		{
			get
			{
				return this._AmSuffixID;
			}
			set
			{
				if ((this._AmSuffixID != value))
				{
					this.OnAmSuffixIDChanging(value);
					this.SendPropertyChanging();
					this._AmSuffixID = value;
					this.SendPropertyChanged("AmSuffixID");
					this.OnAmSuffixIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDVeteran", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool DDVeteran
		{
			get
			{
				return this._DDVeteran;
			}
			set
			{
				if ((this._DDVeteran != value))
				{
					this.OnDDVeteranChanging(value);
					this.SendPropertyChanging();
					this._DDVeteran = value;
					this.SendPropertyChanged("DDVeteran");
					this.OnDDVeteranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSAcademicGPA", DbType="Decimal(11,6)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> HSAcademicGPA
		{
			get
			{
				return this._HSAcademicGPA;
			}
			set
			{
				if ((this._HSAcademicGPA != value))
				{
					this.OnHSAcademicGPAChanging(value);
					this.SendPropertyChanging();
					this._HSAcademicGPA = value;
					this.SendPropertyChanged("HSAcademicGPA");
					this.OnHSAcademicGPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AthleticID", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string AthleticID
		{
			get
			{
				return this._AthleticID;
			}
			set
			{
				if ((this._AthleticID != value))
				{
					this.OnAthleticIDChanging(value);
					this.SendPropertyChanging();
					this._AthleticID = value;
					this.SendPropertyChanged("AthleticID");
					this.OnAthleticIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InDistrict", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool InDistrict
		{
			get
			{
				return this._InDistrict;
			}
			set
			{
				if ((this._InDistrict != value))
				{
					this.OnInDistrictChanging(value);
					this.SendPropertyChanging();
					this._InDistrict = value;
					this.SendPropertyChanged("InDistrict");
					this.OnInDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faGradPlusCounselingDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> faGradPlusCounselingDate
		{
			get
			{
				return this._faGradPlusCounselingDate;
			}
			set
			{
				if ((this._faGradPlusCounselingDate != value))
				{
					this.OnfaGradPlusCounselingDateChanging(value);
					this.SendPropertyChanging();
					this._faGradPlusCounselingDate = value;
					this.SendPropertyChanged("faGradPlusCounselingDate");
					this.OnfaGradPlusCounselingDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultStipendsToEFT", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool DefaultStipendsToEFT
		{
			get
			{
				return this._DefaultStipendsToEFT;
			}
			set
			{
				if ((this._DefaultStipendsToEFT != value))
				{
					this.OnDefaultStipendsToEFTChanging(value);
					this.SendPropertyChanging();
					this._DefaultStipendsToEFT = value;
					this.SendPropertyChanged("DefaultStipendsToEFT");
					this.OnDefaultStipendsToEFTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI", AutoSync=AutoSync.Always, DbType="VarChar(1) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string MI
		{
			get
			{
				return this._MI;
			}
			set
			{
				if ((this._MI != value))
				{
					this.OnMIChanging(value);
					this.SendPropertyChanging();
					this._MI = value;
					this.SendPropertyChanged("MI");
					this.OnMIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
